# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from service.service_spec import reading_files_pb2 as service_dot_service__spec_dot_reading__files__pb2


class MessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.printing = channel.unary_unary(
                '/Message/printing',
                request_serializer=service_dot_service__spec_dot_reading__files__pb2.Input.SerializeToString,
                response_deserializer=service_dot_service__spec_dot_reading__files__pb2.Output.FromString,
                )


class MessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def printing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'printing': grpc.unary_unary_rpc_method_handler(
                    servicer.printing,
                    request_deserializer=service_dot_service__spec_dot_reading__files__pb2.Input.FromString,
                    response_serializer=service_dot_service__spec_dot_reading__files__pb2.Output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Message', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Message(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def printing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/printing',
            service_dot_service__spec_dot_reading__files__pb2.Input.SerializeToString,
            service_dot_service__spec_dot_reading__files__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
